#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|fix|chore|refactor|docs|style|test|perf|ci|build|revert): .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "--->   Wrong commit message!  "
  echo "-"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood> <what was done>"
  echo "Allowed verbs in imperative mood: feat, fix, chore, refactor, docs, style, test, perf, ci, build, revert."
  echo "Example: 'fix: fix foo to enable bar'"
  echo "-"
  echo "-"
  echo "-> Your commit message was:"
  echo "-> "$message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  echo "-"
  exit 1
fi
